# Change these first
owner: Clyzer # Your GitHub organization or username, where this repository lives
repo: mangos-status-page # The name of this repository

sites:
  - name: Servicio multijugador de Mojang
    url: http://session.minecraft.net
    expectedStatusCodes:
      - 404
  - name: Minecraft Skins
    url: https://textures.minecraft.net
    expectedStatusCodes:
      - 400
  - name: "API pública de Mojang"
    url: https://api.mojang.com/
  - name: Sitio web de cuentas de Mojang
    url: https://account.mojang.com/login
    expectedStatusCodes:
      - 403
      - 200
  - name: Servidor Microsoft OAuth
    url: https://login.microsoftonline.com/consumers/oauth2/v2.0/token
  - name: Servidor de autenticación de Xbox Live
    url: https://user.auth.xboxlive.com/user/authenticate
    expectedStatusCodes:
      - 405
  - name: Control de acceso a Xbox Live
    url: https://xsts.auth.xboxlive.com/xsts/authorize
    expectedStatusCodes:
      - 405
  - name: Microsoft Minecraft API
    url: https://api.minecraftservices.com/authentication/login_with_xbox
    expectedStatusCodes:
      - 401
      - 403
  - name: Perfil de Microsoft Minecraft
    url: https://api.minecraftservices.com/minecraft/profile
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: aventiumsoftworks.github.io
  baseUrl: /mangos-status-page
  logoUrl: https://github.com/clyzer/MangoLauncher/raw/master/app/assets/images/SealCircle.png
  name: Página de estado de Imperio Mango
  introTitle: "Mangos Launcher utiliza esta página para obtener el estado de Mojang."
  introMessage: Nosotros no somos Mojang/Microsoft
  navbar:
    - title: Inicio
      href: /mangos-status-page
    - title: Código fuente de mango launcher
      href: https://github.com/clyzer/MangoLauncher

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
